# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm/v7

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Process for the `director` subfolder
      - name: Extract metadata (tags, labels) for Docker (director)
        id: metaDirector
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/bareos-director
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image (director)
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./director
          push: true
          tags: ${{ steps.metaDirector.outputs.tags }}
          labels: ${{ steps.metaDirector.outputs.labels }}
          platforms: linux/arm/v7

      # Process for the `storage` subfolder
      - name: Extract metadata (tags, labels) for Docker (storage)
        id: metaStorage
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/bareos-storage
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image (storage)
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./storage
          push: true
          tags: ${{ steps.metaStorage.outputs.tags }}
          labels: ${{ steps.metaStorage.outputs.labels }}
          platforms: linux/arm/v7

      # Process for the `webui` subfolder
      - name: Extract metadata (tags, labels) for Docker (webui)
        id: metaWebui
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/bareos-webui
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image (webui)
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./webui
          push: true
          tags: ${{ steps.metaWebui.outputs.tags }}
          labels: ${{ steps.metaWebui.outputs.labels }}
          platforms: linux/arm/v7
